/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_1.txt
/my_dir3/SetNewPatEn 0.1
/my_dir2/SetCountsStep 10000
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_2.txt
/my_dir3/SetNewPatEn 0.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_3.txt
/my_dir3/SetNewPatEn 0.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_4.txt
/my_dir3/SetNewPatEn 0.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_5.txt
/my_dir3/SetNewPatEn 0.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_6.txt
/my_dir3/SetNewPatEn 0.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_7.txt
/my_dir3/SetNewPatEn 0.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_8.txt
/my_dir3/SetNewPatEn 0.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_9.txt
/my_dir3/SetNewPatEn 0.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_10.txt
/my_dir3/SetNewPatEn 1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_11.txt
/my_dir3/SetNewPatEn 1.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_12.txt
/my_dir3/SetNewPatEn 1.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_13.txt
/my_dir3/SetNewPatEn 1.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_14.txt
/my_dir3/SetNewPatEn 1.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_15.txt
/my_dir3/SetNewPatEn 1.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_16.txt
/my_dir3/SetNewPatEn 1.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_17.txt
/my_dir3/SetNewPatEn 1.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_18.txt
/my_dir3/SetNewPatEn 1.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_19.txt
/my_dir3/SetNewPatEn 1.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_20.txt
/my_dir3/SetNewPatEn 2.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_21.txt
/my_dir3/SetNewPatEn 2.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_22.txt
/my_dir3/SetNewPatEn 2.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_23.txt
/my_dir3/SetNewPatEn 2.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_24.txt
/my_dir3/SetNewPatEn 2.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_25.txt
/my_dir3/SetNewPatEn 2.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_26.txt
/my_dir3/SetNewPatEn 2.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_27.txt
/my_dir3/SetNewPatEn 2.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_28.txt
/my_dir3/SetNewPatEn 2.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_29.txt
/my_dir3/SetNewPatEn 2.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_30.txt
/my_dir3/SetNewPatEn 3.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_31.txt
/my_dir3/SetNewPatEn 3.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_32.txt
/my_dir3/SetNewPatEn 3.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_33.txt
/my_dir3/SetNewPatEn 3.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_34.txt
/my_dir3/SetNewPatEn 3.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_35.txt
/my_dir3/SetNewPatEn 3.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_36.txt
/my_dir3/SetNewPatEn 3.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_37.txt
/my_dir3/SetNewPatEn 3.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_38.txt
/my_dir3/SetNewPatEn 3.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_39.txt
/my_dir3/SetNewPatEn 3.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_40.txt
/my_dir3/SetNewPatEn 4.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_41.txt
/my_dir3/SetNewPatEn 4.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_42.txt
/my_dir3/SetNewPatEn 4.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_43.txt
/my_dir3/SetNewPatEn 4.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_44.txt
/my_dir3/SetNewPatEn 4.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_45.txt
/my_dir3/SetNewPatEn 4.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_46.txt
/my_dir3/SetNewPatEn 4.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_47.txt
/my_dir3/SetNewPatEn 4.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_48.txt
/my_dir3/SetNewPatEn 4.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_49.txt
/my_dir3/SetNewPatEn 4.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_50.txt
/my_dir3/SetNewPatEn 5.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_51.txt
/my_dir3/SetNewPatEn 5.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_52.txt
/my_dir3/SetNewPatEn 5.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_53.txt
/my_dir3/SetNewPatEn 5.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_54.txt
/my_dir3/SetNewPatEn 5.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_55.txt
/my_dir3/SetNewPatEn 5.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_56.txt
/my_dir3/SetNewPatEn 5.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_57.txt
/my_dir3/SetNewPatEn 5.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_58.txt
/my_dir3/SetNewPatEn 5.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_59.txt
/my_dir3/SetNewPatEn 5.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_60.txt
/my_dir3/SetNewPatEn 6.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_61.txt
/my_dir3/SetNewPatEn 6.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_62.txt
/my_dir3/SetNewPatEn 6.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_63.txt
/my_dir3/SetNewPatEn 6.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_64.txt
/my_dir3/SetNewPatEn 6.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_65.txt
/my_dir3/SetNewPatEn 6.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_66.txt
/my_dir3/SetNewPatEn 6.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_67.txt
/my_dir3/SetNewPatEn 6.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_68.txt
/my_dir3/SetNewPatEn 6.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_69.txt
/my_dir3/SetNewPatEn 6.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_70.txt
/my_dir3/SetNewPatEn 7.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_71.txt
/my_dir3/SetNewPatEn 7.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_72.txt
/my_dir3/SetNewPatEn 7.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_73.txt
/my_dir3/SetNewPatEn 7.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_74.txt
/my_dir3/SetNewPatEn 7.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_75.txt
/my_dir3/SetNewPatEn 7.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_76.txt
/my_dir3/SetNewPatEn 7.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_77.txt
/my_dir3/SetNewPatEn 7.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_78.txt
/my_dir3/SetNewPatEn 7.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_79.txt
/my_dir3/SetNewPatEn 7.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_80.txt
/my_dir3/SetNewPatEn 8.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_81.txt
/my_dir3/SetNewPatEn 8.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_82.txt
/my_dir3/SetNewPatEn 8.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_83.txt
/my_dir3/SetNewPatEn 8.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_84.txt
/my_dir3/SetNewPatEn 8.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_85.txt
/my_dir3/SetNewPatEn 8.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_86.txt
/my_dir3/SetNewPatEn 8.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_87.txt
/my_dir3/SetNewPatEn 8.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_88.txt
/my_dir3/SetNewPatEn 8.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_89.txt
/my_dir3/SetNewPatEn 8.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_90.txt
/my_dir3/SetNewPatEn 9.0
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_91.txt
/my_dir3/SetNewPatEn 9.1
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_92.txt
/my_dir3/SetNewPatEn 9.2
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_93.txt
/my_dir3/SetNewPatEn 9.3
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_94.txt
/my_dir3/SetNewPatEn 9.4
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_95.txt
/my_dir3/SetNewPatEn 9.5
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_96.txt
/my_dir3/SetNewPatEn 9.6
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_97.txt
/my_dir3/SetNewPatEn 9.7
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_98.txt
/my_dir3/SetNewPatEn 9.8
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_99.txt
/my_dir3/SetNewPatEn 9.9
/run/beamOn 100000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_100.txt
/my_dir3/SetNewPatEn 10.0
/run/beamOn 100000