/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_1.txt
/my_dir2/SetCountsStep 100000
/my_dir3/SetNewPatEn 13
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_2.txt
/my_dir3/SetNewPatEn 13.02
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_3.txt
/my_dir3/SetNewPatEn 13.04
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_4.txt
/my_dir3/SetNewPatEn 13.06
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_5.txt
/my_dir3/SetNewPatEn 13.08
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_6.txt
/my_dir3/SetNewPatEn 13.1
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_7.txt
/my_dir3/SetNewPatEn 13.12
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_8.txt
/my_dir3/SetNewPatEn 13.14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_9.txt
/my_dir3/SetNewPatEn 13.16
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_10.txt
/my_dir3/SetNewPatEn 13.18
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_11.txt
/my_dir3/SetNewPatEn 13.2
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_12.txt
/my_dir3/SetNewPatEn 13.22
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_13.txt
/my_dir3/SetNewPatEn 13.24
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_14.txt
/my_dir3/SetNewPatEn 13.26
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_15.txt
/my_dir3/SetNewPatEn 13.28
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_16.txt
/my_dir3/SetNewPatEn 13.3
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_17.txt
/my_dir3/SetNewPatEn 13.32
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_18.txt
/my_dir3/SetNewPatEn 13.34
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_19.txt
/my_dir3/SetNewPatEn 13.36
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_20.txt
/my_dir3/SetNewPatEn 13.38
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_21.txt
/my_dir3/SetNewPatEn 13.4
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_22.txt
/my_dir3/SetNewPatEn 13.42
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_23.txt
/my_dir3/SetNewPatEn 13.44
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_24.txt
/my_dir3/SetNewPatEn 13.46
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_25.txt
/my_dir3/SetNewPatEn 13.48
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_26.txt
/my_dir3/SetNewPatEn 13.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_27.txt
/my_dir3/SetNewPatEn 13.52
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_28.txt
/my_dir3/SetNewPatEn 13.54
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_29.txt
/my_dir3/SetNewPatEn 13.56
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_30.txt
/my_dir3/SetNewPatEn 13.58
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_31.txt
/my_dir3/SetNewPatEn 13.6
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_32.txt
/my_dir3/SetNewPatEn 13.62
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_33.txt
/my_dir3/SetNewPatEn 13.64
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_34.txt
/my_dir3/SetNewPatEn 13.66
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_35.txt
/my_dir3/SetNewPatEn 13.68
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_36.txt
/my_dir3/SetNewPatEn 13.7
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_37.txt
/my_dir3/SetNewPatEn 13.72
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_38.txt
/my_dir3/SetNewPatEn 13.74
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_39.txt
/my_dir3/SetNewPatEn 13.76
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_40.txt
/my_dir3/SetNewPatEn 13.78
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_41.txt
/my_dir3/SetNewPatEn 13.8
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_42.txt
/my_dir3/SetNewPatEn 13.82
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_43.txt
/my_dir3/SetNewPatEn 13.84
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_44.txt
/my_dir3/SetNewPatEn 13.86
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_45.txt
/my_dir3/SetNewPatEn 13.88
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_46.txt
/my_dir3/SetNewPatEn 13.9
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_47.txt
/my_dir3/SetNewPatEn 13.92
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_48.txt
/my_dir3/SetNewPatEn 13.94
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_49.txt
/my_dir3/SetNewPatEn 13.96
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_50.txt
/my_dir3/SetNewPatEn 13.98
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_51.txt
/my_dir3/SetNewPatEn 14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_52.txt
/my_dir3/SetNewPatEn 14.02
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_53.txt
/my_dir3/SetNewPatEn 14.04
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_54.txt
/my_dir3/SetNewPatEn 14.06
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_55.txt
/my_dir3/SetNewPatEn 14.08
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_56.txt
/my_dir3/SetNewPatEn 14.1
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_57.txt
/my_dir3/SetNewPatEn 14.12
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_58.txt
/my_dir3/SetNewPatEn 14.14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_59.txt
/my_dir3/SetNewPatEn 14.16
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_60.txt
/my_dir3/SetNewPatEn 14.18
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_61.txt
/my_dir3/SetNewPatEn 14.2
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_62.txt
/my_dir3/SetNewPatEn 14.22
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_63.txt
/my_dir3/SetNewPatEn 14.24
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_64.txt
/my_dir3/SetNewPatEn 14.26
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_65.txt
/my_dir3/SetNewPatEn 14.28
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_66.txt
/my_dir3/SetNewPatEn 14.3
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_67.txt
/my_dir3/SetNewPatEn 14.32
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_68.txt
/my_dir3/SetNewPatEn 14.34
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_69.txt
/my_dir3/SetNewPatEn 14.36
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_70.txt
/my_dir3/SetNewPatEn 14.38
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_71.txt
/my_dir3/SetNewPatEn 14.4
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_72.txt
/my_dir3/SetNewPatEn 14.42
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_73.txt
/my_dir3/SetNewPatEn 14.44
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_74.txt
/my_dir3/SetNewPatEn 14.46
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_75.txt
/my_dir3/SetNewPatEn 14.48
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_76.txt
/my_dir3/SetNewPatEn 14.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_77.txt
/my_dir3/SetNewPatEn 14.52
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_78.txt
/my_dir3/SetNewPatEn 14.54
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_79.txt
/my_dir3/SetNewPatEn 14.56
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_80.txt
/my_dir3/SetNewPatEn 14.58
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_81.txt
/my_dir3/SetNewPatEn 14.6
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_82.txt
/my_dir3/SetNewPatEn 14.62
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_83.txt
/my_dir3/SetNewPatEn 14.64
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_84.txt
/my_dir3/SetNewPatEn 14.66
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_85.txt
/my_dir3/SetNewPatEn 14.68
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_86.txt
/my_dir3/SetNewPatEn 14.7
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_87.txt
/my_dir3/SetNewPatEn 14.72
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_88.txt
/my_dir3/SetNewPatEn 14.74
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_89.txt
/my_dir3/SetNewPatEn 14.76
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_90.txt
/my_dir3/SetNewPatEn 14.78
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_91.txt
/my_dir3/SetNewPatEn 14.8
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_92.txt
/my_dir3/SetNewPatEn 14.82
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_93.txt
/my_dir3/SetNewPatEn 14.84
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_94.txt
/my_dir3/SetNewPatEn 14.86
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_95.txt
/my_dir3/SetNewPatEn 14.88
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_96.txt
/my_dir3/SetNewPatEn 14.9
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_97.txt
/my_dir3/SetNewPatEn 14.92
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_98.txt
/my_dir3/SetNewPatEn 14.94
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_99.txt
/my_dir3/SetNewPatEn 14.96
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_100.txt
/my_dir3/SetNewPatEn 14.98
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_101.txt
/my_dir3/SetNewPatEn 15
/run/beamOn 5000000