/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_1.txt
/my_dir2/SetCountsStep 100000
/my_dir3/SetNewPatEn 0.01
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_2.txt
/my_dir3/SetNewPatEn 0.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_3.txt
/my_dir3/SetNewPatEn 0.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_4.txt
/my_dir3/SetNewPatEn 0.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_5.txt
/my_dir3/SetNewPatEn 1
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_6.txt
/my_dir3/SetNewPatEn 1.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_7.txt
/my_dir3/SetNewPatEn 1.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_8.txt
/my_dir3/SetNewPatEn 1.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_9.txt
/my_dir3/SetNewPatEn 2
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_10.txt
/my_dir3/SetNewPatEn 2.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_11.txt
/my_dir3/SetNewPatEn 2.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_12.txt
/my_dir3/SetNewPatEn 2.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_13.txt
/my_dir3/SetNewPatEn 3
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_14.txt
/my_dir3/SetNewPatEn 3.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_15.txt
/my_dir3/SetNewPatEn 3.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_16.txt
/my_dir3/SetNewPatEn 3.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_17.txt
/my_dir3/SetNewPatEn 4
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_18.txt
/my_dir3/SetNewPatEn 4.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_19.txt
/my_dir3/SetNewPatEn 4.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_20.txt
/my_dir3/SetNewPatEn 4.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_21.txt
/my_dir3/SetNewPatEn 5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_22.txt
/my_dir3/SetNewPatEn 5.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_23.txt
/my_dir3/SetNewPatEn 5.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_24.txt
/my_dir3/SetNewPatEn 5.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_25.txt
/my_dir3/SetNewPatEn 6
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_26.txt
/my_dir3/SetNewPatEn 6.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_27.txt
/my_dir3/SetNewPatEn 6.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_28.txt
/my_dir3/SetNewPatEn 6.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_29.txt
/my_dir3/SetNewPatEn 7
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_30.txt
/my_dir3/SetNewPatEn 7.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_31.txt
/my_dir3/SetNewPatEn 7.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_32.txt
/my_dir3/SetNewPatEn 7.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_33.txt
/my_dir3/SetNewPatEn 8
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_34.txt
/my_dir3/SetNewPatEn 8.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_35.txt
/my_dir3/SetNewPatEn 8.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_36.txt
/my_dir3/SetNewPatEn 8.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_37.txt
/my_dir3/SetNewPatEn 9
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_38.txt
/my_dir3/SetNewPatEn 9.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_39.txt
/my_dir3/SetNewPatEn 9.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_40.txt
/my_dir3/SetNewPatEn 9.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_41.txt
/my_dir3/SetNewPatEn 10
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_42.txt
/my_dir3/SetNewPatEn 10.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_43.txt
/my_dir3/SetNewPatEn 10.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_44.txt
/my_dir3/SetNewPatEn 10.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_45.txt
/my_dir3/SetNewPatEn 11
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_46.txt
/my_dir3/SetNewPatEn 11.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_47.txt
/my_dir3/SetNewPatEn 11.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_48.txt
/my_dir3/SetNewPatEn 11.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_49.txt
/my_dir3/SetNewPatEn 12
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_50.txt
/my_dir3/SetNewPatEn 12.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_51.txt
/my_dir3/SetNewPatEn 12.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_52.txt
/my_dir3/SetNewPatEn 12.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_53.txt
/my_dir3/SetNewPatEn 13
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_54.txt
/my_dir3/SetNewPatEn 13.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_55.txt
/my_dir3/SetNewPatEn 13.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_56.txt
/my_dir3/SetNewPatEn 13.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_57.txt
/my_dir3/SetNewPatEn 14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_58.txt
/my_dir3/SetNewPatEn 14.25
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_59.txt
/my_dir3/SetNewPatEn 14.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_60.txt
/my_dir3/SetNewPatEn 14.75
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_61.txt
/my_dir3/SetNewPatEn 15
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_62.txt
/my_dir3/SetNewPatEn 15.25
/run/beamOn 5000000
