/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_1.txt
/my_dir2/SetCountsStep 100000
/my_dir3/SetNewPatEn 13
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_2.txt
/my_dir3/SetNewPatEn 13.004
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_3.txt
/my_dir3/SetNewPatEn 13.008
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_4.txt
/my_dir3/SetNewPatEn 13.012
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_5.txt
/my_dir3/SetNewPatEn 13.016
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_6.txt
/my_dir3/SetNewPatEn 13.02
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_7.txt
/my_dir3/SetNewPatEn 13.024
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_8.txt
/my_dir3/SetNewPatEn 13.028
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_9.txt
/my_dir3/SetNewPatEn 13.032
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_10.txt
/my_dir3/SetNewPatEn 13.036
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_11.txt
/my_dir3/SetNewPatEn 13.04
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_12.txt
/my_dir3/SetNewPatEn 13.044
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_13.txt
/my_dir3/SetNewPatEn 13.048
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_14.txt
/my_dir3/SetNewPatEn 13.052
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_15.txt
/my_dir3/SetNewPatEn 13.056
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_16.txt
/my_dir3/SetNewPatEn 13.06
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_17.txt
/my_dir3/SetNewPatEn 13.064
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_18.txt
/my_dir3/SetNewPatEn 13.068
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_19.txt
/my_dir3/SetNewPatEn 13.072
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_20.txt
/my_dir3/SetNewPatEn 13.076
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_21.txt
/my_dir3/SetNewPatEn 13.08
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_22.txt
/my_dir3/SetNewPatEn 13.084
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_23.txt
/my_dir3/SetNewPatEn 13.088
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_24.txt
/my_dir3/SetNewPatEn 13.092
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_25.txt
/my_dir3/SetNewPatEn 13.096
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_26.txt
/my_dir3/SetNewPatEn 13.1
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_27.txt
/my_dir3/SetNewPatEn 13.104
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_28.txt
/my_dir3/SetNewPatEn 13.108
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_29.txt
/my_dir3/SetNewPatEn 13.112
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_30.txt
/my_dir3/SetNewPatEn 13.116
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_31.txt
/my_dir3/SetNewPatEn 13.12
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_32.txt
/my_dir3/SetNewPatEn 13.124
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_33.txt
/my_dir3/SetNewPatEn 13.128
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_34.txt
/my_dir3/SetNewPatEn 13.132
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_35.txt
/my_dir3/SetNewPatEn 13.136
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_36.txt
/my_dir3/SetNewPatEn 13.14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_37.txt
/my_dir3/SetNewPatEn 13.144
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_38.txt
/my_dir3/SetNewPatEn 13.148
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_39.txt
/my_dir3/SetNewPatEn 13.152
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_40.txt
/my_dir3/SetNewPatEn 13.156
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_41.txt
/my_dir3/SetNewPatEn 13.16
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_42.txt
/my_dir3/SetNewPatEn 13.164
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_43.txt
/my_dir3/SetNewPatEn 13.168
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_44.txt
/my_dir3/SetNewPatEn 13.172
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_45.txt
/my_dir3/SetNewPatEn 13.176
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_46.txt
/my_dir3/SetNewPatEn 13.18
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_47.txt
/my_dir3/SetNewPatEn 13.184
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_48.txt
/my_dir3/SetNewPatEn 13.188
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_49.txt
/my_dir3/SetNewPatEn 13.192
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_50.txt
/my_dir3/SetNewPatEn 13.196
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_51.txt
/my_dir3/SetNewPatEn 13.2
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_52.txt
/my_dir3/SetNewPatEn 13.204
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_53.txt
/my_dir3/SetNewPatEn 13.208
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_54.txt
/my_dir3/SetNewPatEn 13.212
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_55.txt
/my_dir3/SetNewPatEn 13.216
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_56.txt
/my_dir3/SetNewPatEn 13.22
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_57.txt
/my_dir3/SetNewPatEn 13.224
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_58.txt
/my_dir3/SetNewPatEn 13.228
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_59.txt
/my_dir3/SetNewPatEn 13.232
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_60.txt
/my_dir3/SetNewPatEn 13.236
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_61.txt
/my_dir3/SetNewPatEn 13.24
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_62.txt
/my_dir3/SetNewPatEn 13.244
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_63.txt
/my_dir3/SetNewPatEn 13.248
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_64.txt
/my_dir3/SetNewPatEn 13.252
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_65.txt
/my_dir3/SetNewPatEn 13.256
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_66.txt
/my_dir3/SetNewPatEn 13.26
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_67.txt
/my_dir3/SetNewPatEn 13.264
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_68.txt
/my_dir3/SetNewPatEn 13.268
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_69.txt
/my_dir3/SetNewPatEn 13.272
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_70.txt
/my_dir3/SetNewPatEn 13.276
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_71.txt
/my_dir3/SetNewPatEn 13.28
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_72.txt
/my_dir3/SetNewPatEn 13.284
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_73.txt
/my_dir3/SetNewPatEn 13.288
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_74.txt
/my_dir3/SetNewPatEn 13.292
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_75.txt
/my_dir3/SetNewPatEn 13.296
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_76.txt
/my_dir3/SetNewPatEn 13.3
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_77.txt
/my_dir3/SetNewPatEn 13.304
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_78.txt
/my_dir3/SetNewPatEn 13.308
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_79.txt
/my_dir3/SetNewPatEn 13.312
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_80.txt
/my_dir3/SetNewPatEn 13.316
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_81.txt
/my_dir3/SetNewPatEn 13.32
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_82.txt
/my_dir3/SetNewPatEn 13.324
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_83.txt
/my_dir3/SetNewPatEn 13.328
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_84.txt
/my_dir3/SetNewPatEn 13.332
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_85.txt
/my_dir3/SetNewPatEn 13.336
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_86.txt
/my_dir3/SetNewPatEn 13.34
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_87.txt
/my_dir3/SetNewPatEn 13.344
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_88.txt
/my_dir3/SetNewPatEn 13.348
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_89.txt
/my_dir3/SetNewPatEn 13.352
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_90.txt
/my_dir3/SetNewPatEn 13.356
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_91.txt
/my_dir3/SetNewPatEn 13.36
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_92.txt
/my_dir3/SetNewPatEn 13.364
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_93.txt
/my_dir3/SetNewPatEn 13.368
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_94.txt
/my_dir3/SetNewPatEn 13.372
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_95.txt
/my_dir3/SetNewPatEn 13.376
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_96.txt
/my_dir3/SetNewPatEn 13.38
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_97.txt
/my_dir3/SetNewPatEn 13.384
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_98.txt
/my_dir3/SetNewPatEn 13.388
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_99.txt
/my_dir3/SetNewPatEn 13.392
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_100.txt
/my_dir3/SetNewPatEn 13.396
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_101.txt
/my_dir3/SetNewPatEn 13.4
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_102.txt
/my_dir3/SetNewPatEn 13.404
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_103.txt
/my_dir3/SetNewPatEn 13.408
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_104.txt
/my_dir3/SetNewPatEn 13.412
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_105.txt
/my_dir3/SetNewPatEn 13.416
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_106.txt
/my_dir3/SetNewPatEn 13.42
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_107.txt
/my_dir3/SetNewPatEn 13.424
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_108.txt
/my_dir3/SetNewPatEn 13.428
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_109.txt
/my_dir3/SetNewPatEn 13.432
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_110.txt
/my_dir3/SetNewPatEn 13.436
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_111.txt
/my_dir3/SetNewPatEn 13.44
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_112.txt
/my_dir3/SetNewPatEn 13.444
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_113.txt
/my_dir3/SetNewPatEn 13.448
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_114.txt
/my_dir3/SetNewPatEn 13.452
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_115.txt
/my_dir3/SetNewPatEn 13.456
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_116.txt
/my_dir3/SetNewPatEn 13.46
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_117.txt
/my_dir3/SetNewPatEn 13.464
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_118.txt
/my_dir3/SetNewPatEn 13.468
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_119.txt
/my_dir3/SetNewPatEn 13.472
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_120.txt
/my_dir3/SetNewPatEn 13.476
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_121.txt
/my_dir3/SetNewPatEn 13.48
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_122.txt
/my_dir3/SetNewPatEn 13.484
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_123.txt
/my_dir3/SetNewPatEn 13.488
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_124.txt
/my_dir3/SetNewPatEn 13.492
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_125.txt
/my_dir3/SetNewPatEn 13.496
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_126.txt
/my_dir3/SetNewPatEn 13.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_127.txt
/my_dir3/SetNewPatEn 13.504
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_128.txt
/my_dir3/SetNewPatEn 13.508
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_129.txt
/my_dir3/SetNewPatEn 13.512
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_130.txt
/my_dir3/SetNewPatEn 13.516
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_131.txt
/my_dir3/SetNewPatEn 13.52
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_132.txt
/my_dir3/SetNewPatEn 13.524
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_133.txt
/my_dir3/SetNewPatEn 13.528
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_134.txt
/my_dir3/SetNewPatEn 13.532
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_135.txt
/my_dir3/SetNewPatEn 13.536
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_136.txt
/my_dir3/SetNewPatEn 13.54
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_137.txt
/my_dir3/SetNewPatEn 13.544
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_138.txt
/my_dir3/SetNewPatEn 13.548
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_139.txt
/my_dir3/SetNewPatEn 13.552
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_140.txt
/my_dir3/SetNewPatEn 13.556
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_141.txt
/my_dir3/SetNewPatEn 13.56
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_142.txt
/my_dir3/SetNewPatEn 13.564
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_143.txt
/my_dir3/SetNewPatEn 13.568
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_144.txt
/my_dir3/SetNewPatEn 13.572
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_145.txt
/my_dir3/SetNewPatEn 13.576
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_146.txt
/my_dir3/SetNewPatEn 13.58
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_147.txt
/my_dir3/SetNewPatEn 13.584
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_148.txt
/my_dir3/SetNewPatEn 13.588
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_149.txt
/my_dir3/SetNewPatEn 13.592
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_150.txt
/my_dir3/SetNewPatEn 13.596
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_151.txt
/my_dir3/SetNewPatEn 13.6
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_152.txt
/my_dir3/SetNewPatEn 13.604
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_153.txt
/my_dir3/SetNewPatEn 13.608
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_154.txt
/my_dir3/SetNewPatEn 13.612
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_155.txt
/my_dir3/SetNewPatEn 13.616
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_156.txt
/my_dir3/SetNewPatEn 13.62
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_157.txt
/my_dir3/SetNewPatEn 13.624
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_158.txt
/my_dir3/SetNewPatEn 13.628
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_159.txt
/my_dir3/SetNewPatEn 13.632
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_160.txt
/my_dir3/SetNewPatEn 13.636
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_161.txt
/my_dir3/SetNewPatEn 13.64
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_162.txt
/my_dir3/SetNewPatEn 13.644
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_163.txt
/my_dir3/SetNewPatEn 13.648
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_164.txt
/my_dir3/SetNewPatEn 13.652
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_165.txt
/my_dir3/SetNewPatEn 13.656
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_166.txt
/my_dir3/SetNewPatEn 13.66
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_167.txt
/my_dir3/SetNewPatEn 13.664
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_168.txt
/my_dir3/SetNewPatEn 13.668
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_169.txt
/my_dir3/SetNewPatEn 13.672
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_170.txt
/my_dir3/SetNewPatEn 13.676
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_171.txt
/my_dir3/SetNewPatEn 13.68
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_172.txt
/my_dir3/SetNewPatEn 13.684
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_173.txt
/my_dir3/SetNewPatEn 13.688
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_174.txt
/my_dir3/SetNewPatEn 13.692
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_175.txt
/my_dir3/SetNewPatEn 13.696
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_176.txt
/my_dir3/SetNewPatEn 13.7
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_177.txt
/my_dir3/SetNewPatEn 13.704
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_178.txt
/my_dir3/SetNewPatEn 13.708
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_179.txt
/my_dir3/SetNewPatEn 13.712
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_180.txt
/my_dir3/SetNewPatEn 13.716
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_181.txt
/my_dir3/SetNewPatEn 13.72
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_182.txt
/my_dir3/SetNewPatEn 13.724
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_183.txt
/my_dir3/SetNewPatEn 13.728
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_184.txt
/my_dir3/SetNewPatEn 13.732
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_185.txt
/my_dir3/SetNewPatEn 13.736
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_186.txt
/my_dir3/SetNewPatEn 13.74
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_187.txt
/my_dir3/SetNewPatEn 13.744
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_188.txt
/my_dir3/SetNewPatEn 13.748
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_189.txt
/my_dir3/SetNewPatEn 13.752
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_190.txt
/my_dir3/SetNewPatEn 13.756
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_191.txt
/my_dir3/SetNewPatEn 13.76
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_192.txt
/my_dir3/SetNewPatEn 13.764
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_193.txt
/my_dir3/SetNewPatEn 13.768
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_194.txt
/my_dir3/SetNewPatEn 13.772
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_195.txt
/my_dir3/SetNewPatEn 13.776
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_196.txt
/my_dir3/SetNewPatEn 13.78
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_197.txt
/my_dir3/SetNewPatEn 13.784
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_198.txt
/my_dir3/SetNewPatEn 13.788
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_199.txt
/my_dir3/SetNewPatEn 13.792
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_200.txt
/my_dir3/SetNewPatEn 13.796
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_201.txt
/my_dir3/SetNewPatEn 13.8
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_202.txt
/my_dir3/SetNewPatEn 13.804
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_203.txt
/my_dir3/SetNewPatEn 13.808
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_204.txt
/my_dir3/SetNewPatEn 13.812
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_205.txt
/my_dir3/SetNewPatEn 13.816
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_206.txt
/my_dir3/SetNewPatEn 13.82
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_207.txt
/my_dir3/SetNewPatEn 13.824
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_208.txt
/my_dir3/SetNewPatEn 13.828
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_209.txt
/my_dir3/SetNewPatEn 13.832
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_210.txt
/my_dir3/SetNewPatEn 13.836
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_211.txt
/my_dir3/SetNewPatEn 13.84
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_212.txt
/my_dir3/SetNewPatEn 13.844
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_213.txt
/my_dir3/SetNewPatEn 13.848
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_214.txt
/my_dir3/SetNewPatEn 13.852
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_215.txt
/my_dir3/SetNewPatEn 13.856
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_216.txt
/my_dir3/SetNewPatEn 13.86
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_217.txt
/my_dir3/SetNewPatEn 13.864
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_218.txt
/my_dir3/SetNewPatEn 13.868
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_219.txt
/my_dir3/SetNewPatEn 13.872
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_220.txt
/my_dir3/SetNewPatEn 13.876
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_221.txt
/my_dir3/SetNewPatEn 13.88
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_222.txt
/my_dir3/SetNewPatEn 13.884
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_223.txt
/my_dir3/SetNewPatEn 13.888
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_224.txt
/my_dir3/SetNewPatEn 13.892
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_225.txt
/my_dir3/SetNewPatEn 13.896
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_226.txt
/my_dir3/SetNewPatEn 13.9
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_227.txt
/my_dir3/SetNewPatEn 13.904
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_228.txt
/my_dir3/SetNewPatEn 13.908
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_229.txt
/my_dir3/SetNewPatEn 13.912
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_230.txt
/my_dir3/SetNewPatEn 13.916
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_231.txt
/my_dir3/SetNewPatEn 13.92
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_232.txt
/my_dir3/SetNewPatEn 13.924
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_233.txt
/my_dir3/SetNewPatEn 13.928
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_234.txt
/my_dir3/SetNewPatEn 13.932
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_235.txt
/my_dir3/SetNewPatEn 13.936
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_236.txt
/my_dir3/SetNewPatEn 13.94
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_237.txt
/my_dir3/SetNewPatEn 13.944
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_238.txt
/my_dir3/SetNewPatEn 13.948
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_239.txt
/my_dir3/SetNewPatEn 13.952
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_240.txt
/my_dir3/SetNewPatEn 13.956
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_241.txt
/my_dir3/SetNewPatEn 13.96
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_242.txt
/my_dir3/SetNewPatEn 13.964
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_243.txt
/my_dir3/SetNewPatEn 13.968
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_244.txt
/my_dir3/SetNewPatEn 13.972
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_245.txt
/my_dir3/SetNewPatEn 13.976
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_246.txt
/my_dir3/SetNewPatEn 13.98
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_247.txt
/my_dir3/SetNewPatEn 13.984
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_248.txt
/my_dir3/SetNewPatEn 13.988
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_249.txt
/my_dir3/SetNewPatEn 13.992
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_250.txt
/my_dir3/SetNewPatEn 13.996
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_251.txt
/my_dir3/SetNewPatEn 14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_252.txt
/my_dir3/SetNewPatEn 14.004
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_253.txt
/my_dir3/SetNewPatEn 14.008
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_254.txt
/my_dir3/SetNewPatEn 14.012
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_255.txt
/my_dir3/SetNewPatEn 14.016
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_256.txt
/my_dir3/SetNewPatEn 14.02
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_257.txt
/my_dir3/SetNewPatEn 14.024
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_258.txt
/my_dir3/SetNewPatEn 14.028
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_259.txt
/my_dir3/SetNewPatEn 14.032
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_260.txt
/my_dir3/SetNewPatEn 14.036
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_261.txt
/my_dir3/SetNewPatEn 14.04
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_262.txt
/my_dir3/SetNewPatEn 14.044
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_263.txt
/my_dir3/SetNewPatEn 14.048
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_264.txt
/my_dir3/SetNewPatEn 14.052
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_265.txt
/my_dir3/SetNewPatEn 14.056
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_266.txt
/my_dir3/SetNewPatEn 14.06
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_267.txt
/my_dir3/SetNewPatEn 14.064
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_268.txt
/my_dir3/SetNewPatEn 14.068
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_269.txt
/my_dir3/SetNewPatEn 14.072
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_270.txt
/my_dir3/SetNewPatEn 14.076
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_271.txt
/my_dir3/SetNewPatEn 14.08
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_272.txt
/my_dir3/SetNewPatEn 14.084
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_273.txt
/my_dir3/SetNewPatEn 14.088
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_274.txt
/my_dir3/SetNewPatEn 14.092
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_275.txt
/my_dir3/SetNewPatEn 14.096
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_276.txt
/my_dir3/SetNewPatEn 14.1
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_277.txt
/my_dir3/SetNewPatEn 14.104
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_278.txt
/my_dir3/SetNewPatEn 14.108
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_279.txt
/my_dir3/SetNewPatEn 14.112
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_280.txt
/my_dir3/SetNewPatEn 14.116
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_281.txt
/my_dir3/SetNewPatEn 14.12
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_282.txt
/my_dir3/SetNewPatEn 14.124
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_283.txt
/my_dir3/SetNewPatEn 14.128
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_284.txt
/my_dir3/SetNewPatEn 14.132
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_285.txt
/my_dir3/SetNewPatEn 14.136
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_286.txt
/my_dir3/SetNewPatEn 14.14
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_287.txt
/my_dir3/SetNewPatEn 14.144
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_288.txt
/my_dir3/SetNewPatEn 14.148
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_289.txt
/my_dir3/SetNewPatEn 14.152
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_290.txt
/my_dir3/SetNewPatEn 14.156
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_291.txt
/my_dir3/SetNewPatEn 14.16
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_292.txt
/my_dir3/SetNewPatEn 14.164
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_293.txt
/my_dir3/SetNewPatEn 14.168
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_294.txt
/my_dir3/SetNewPatEn 14.172
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_295.txt
/my_dir3/SetNewPatEn 14.176
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_296.txt
/my_dir3/SetNewPatEn 14.18
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_297.txt
/my_dir3/SetNewPatEn 14.184
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_298.txt
/my_dir3/SetNewPatEn 14.188
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_299.txt
/my_dir3/SetNewPatEn 14.192
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_300.txt
/my_dir3/SetNewPatEn 14.196
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_301.txt
/my_dir3/SetNewPatEn 14.2
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_302.txt
/my_dir3/SetNewPatEn 14.204
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_303.txt
/my_dir3/SetNewPatEn 14.208
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_304.txt
/my_dir3/SetNewPatEn 14.212
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_305.txt
/my_dir3/SetNewPatEn 14.216
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_306.txt
/my_dir3/SetNewPatEn 14.22
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_307.txt
/my_dir3/SetNewPatEn 14.224
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_308.txt
/my_dir3/SetNewPatEn 14.228
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_309.txt
/my_dir3/SetNewPatEn 14.232
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_310.txt
/my_dir3/SetNewPatEn 14.236
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_311.txt
/my_dir3/SetNewPatEn 14.24
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_312.txt
/my_dir3/SetNewPatEn 14.244
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_313.txt
/my_dir3/SetNewPatEn 14.248
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_314.txt
/my_dir3/SetNewPatEn 14.252
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_315.txt
/my_dir3/SetNewPatEn 14.256
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_316.txt
/my_dir3/SetNewPatEn 14.26
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_317.txt
/my_dir3/SetNewPatEn 14.264
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_318.txt
/my_dir3/SetNewPatEn 14.268
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_319.txt
/my_dir3/SetNewPatEn 14.272
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_320.txt
/my_dir3/SetNewPatEn 14.276
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_321.txt
/my_dir3/SetNewPatEn 14.28
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_322.txt
/my_dir3/SetNewPatEn 14.284
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_323.txt
/my_dir3/SetNewPatEn 14.288
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_324.txt
/my_dir3/SetNewPatEn 14.292
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_325.txt
/my_dir3/SetNewPatEn 14.296
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_326.txt
/my_dir3/SetNewPatEn 14.3
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_327.txt
/my_dir3/SetNewPatEn 14.304
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_328.txt
/my_dir3/SetNewPatEn 14.308
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_329.txt
/my_dir3/SetNewPatEn 14.312
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_330.txt
/my_dir3/SetNewPatEn 14.316
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_331.txt
/my_dir3/SetNewPatEn 14.32
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_332.txt
/my_dir3/SetNewPatEn 14.324
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_333.txt
/my_dir3/SetNewPatEn 14.328
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_334.txt
/my_dir3/SetNewPatEn 14.332
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_335.txt
/my_dir3/SetNewPatEn 14.336
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_336.txt
/my_dir3/SetNewPatEn 14.34
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_337.txt
/my_dir3/SetNewPatEn 14.344
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_338.txt
/my_dir3/SetNewPatEn 14.348
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_339.txt
/my_dir3/SetNewPatEn 14.352
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_340.txt
/my_dir3/SetNewPatEn 14.356
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_341.txt
/my_dir3/SetNewPatEn 14.36
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_342.txt
/my_dir3/SetNewPatEn 14.364
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_343.txt
/my_dir3/SetNewPatEn 14.368
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_344.txt
/my_dir3/SetNewPatEn 14.372
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_345.txt
/my_dir3/SetNewPatEn 14.376
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_346.txt
/my_dir3/SetNewPatEn 14.38
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_347.txt
/my_dir3/SetNewPatEn 14.384
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_348.txt
/my_dir3/SetNewPatEn 14.388
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_349.txt
/my_dir3/SetNewPatEn 14.392
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_350.txt
/my_dir3/SetNewPatEn 14.396
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_351.txt
/my_dir3/SetNewPatEn 14.4
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_352.txt
/my_dir3/SetNewPatEn 14.404
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_353.txt
/my_dir3/SetNewPatEn 14.408
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_354.txt
/my_dir3/SetNewPatEn 14.412
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_355.txt
/my_dir3/SetNewPatEn 14.416
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_356.txt
/my_dir3/SetNewPatEn 14.42
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_357.txt
/my_dir3/SetNewPatEn 14.424
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_358.txt
/my_dir3/SetNewPatEn 14.428
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_359.txt
/my_dir3/SetNewPatEn 14.432
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_360.txt
/my_dir3/SetNewPatEn 14.436
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_361.txt
/my_dir3/SetNewPatEn 14.44
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_362.txt
/my_dir3/SetNewPatEn 14.444
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_363.txt
/my_dir3/SetNewPatEn 14.448
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_364.txt
/my_dir3/SetNewPatEn 14.452
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_365.txt
/my_dir3/SetNewPatEn 14.456
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_366.txt
/my_dir3/SetNewPatEn 14.46
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_367.txt
/my_dir3/SetNewPatEn 14.464
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_368.txt
/my_dir3/SetNewPatEn 14.468
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_369.txt
/my_dir3/SetNewPatEn 14.472
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_370.txt
/my_dir3/SetNewPatEn 14.476
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_371.txt
/my_dir3/SetNewPatEn 14.48
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_372.txt
/my_dir3/SetNewPatEn 14.484
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_373.txt
/my_dir3/SetNewPatEn 14.488
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_374.txt
/my_dir3/SetNewPatEn 14.492
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_375.txt
/my_dir3/SetNewPatEn 14.496
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_376.txt
/my_dir3/SetNewPatEn 14.5
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_377.txt
/my_dir3/SetNewPatEn 14.504
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_378.txt
/my_dir3/SetNewPatEn 14.508
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_379.txt
/my_dir3/SetNewPatEn 14.512
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_380.txt
/my_dir3/SetNewPatEn 14.516
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_381.txt
/my_dir3/SetNewPatEn 14.52
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_382.txt
/my_dir3/SetNewPatEn 14.524
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_383.txt
/my_dir3/SetNewPatEn 14.528
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_384.txt
/my_dir3/SetNewPatEn 14.532
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_385.txt
/my_dir3/SetNewPatEn 14.536
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_386.txt
/my_dir3/SetNewPatEn 14.54
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_387.txt
/my_dir3/SetNewPatEn 14.544
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_388.txt
/my_dir3/SetNewPatEn 14.548
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_389.txt
/my_dir3/SetNewPatEn 14.552
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_390.txt
/my_dir3/SetNewPatEn 14.556
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_391.txt
/my_dir3/SetNewPatEn 14.56
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_392.txt
/my_dir3/SetNewPatEn 14.564
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_393.txt
/my_dir3/SetNewPatEn 14.568
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_394.txt
/my_dir3/SetNewPatEn 14.572
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_395.txt
/my_dir3/SetNewPatEn 14.576
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_396.txt
/my_dir3/SetNewPatEn 14.58
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_397.txt
/my_dir3/SetNewPatEn 14.584
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_398.txt
/my_dir3/SetNewPatEn 14.588
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_399.txt
/my_dir3/SetNewPatEn 14.592
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_400.txt
/my_dir3/SetNewPatEn 14.596
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_401.txt
/my_dir3/SetNewPatEn 14.6
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_402.txt
/my_dir3/SetNewPatEn 14.604
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_403.txt
/my_dir3/SetNewPatEn 14.608
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_404.txt
/my_dir3/SetNewPatEn 14.612
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_405.txt
/my_dir3/SetNewPatEn 14.616
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_406.txt
/my_dir3/SetNewPatEn 14.62
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_407.txt
/my_dir3/SetNewPatEn 14.624
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_408.txt
/my_dir3/SetNewPatEn 14.628
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_409.txt
/my_dir3/SetNewPatEn 14.632
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_410.txt
/my_dir3/SetNewPatEn 14.636
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_411.txt
/my_dir3/SetNewPatEn 14.64
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_412.txt
/my_dir3/SetNewPatEn 14.644
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_413.txt
/my_dir3/SetNewPatEn 14.648
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_414.txt
/my_dir3/SetNewPatEn 14.652
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_415.txt
/my_dir3/SetNewPatEn 14.656
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_416.txt
/my_dir3/SetNewPatEn 14.66
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_417.txt
/my_dir3/SetNewPatEn 14.664
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_418.txt
/my_dir3/SetNewPatEn 14.668
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_419.txt
/my_dir3/SetNewPatEn 14.672
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_420.txt
/my_dir3/SetNewPatEn 14.676
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_421.txt
/my_dir3/SetNewPatEn 14.68
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_422.txt
/my_dir3/SetNewPatEn 14.684
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_423.txt
/my_dir3/SetNewPatEn 14.688
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_424.txt
/my_dir3/SetNewPatEn 14.692
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_425.txt
/my_dir3/SetNewPatEn 14.696
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_426.txt
/my_dir3/SetNewPatEn 14.7
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_427.txt
/my_dir3/SetNewPatEn 14.704
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_428.txt
/my_dir3/SetNewPatEn 14.708
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_429.txt
/my_dir3/SetNewPatEn 14.712
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_430.txt
/my_dir3/SetNewPatEn 14.716
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_431.txt
/my_dir3/SetNewPatEn 14.72
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_432.txt
/my_dir3/SetNewPatEn 14.724
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_433.txt
/my_dir3/SetNewPatEn 14.728
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_434.txt
/my_dir3/SetNewPatEn 14.732
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_435.txt
/my_dir3/SetNewPatEn 14.736
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_436.txt
/my_dir3/SetNewPatEn 14.74
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_437.txt
/my_dir3/SetNewPatEn 14.744
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_438.txt
/my_dir3/SetNewPatEn 14.748
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_439.txt
/my_dir3/SetNewPatEn 14.752
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_440.txt
/my_dir3/SetNewPatEn 14.756
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_441.txt
/my_dir3/SetNewPatEn 14.76
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_442.txt
/my_dir3/SetNewPatEn 14.764
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_443.txt
/my_dir3/SetNewPatEn 14.768
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_444.txt
/my_dir3/SetNewPatEn 14.772
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_445.txt
/my_dir3/SetNewPatEn 14.776
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_446.txt
/my_dir3/SetNewPatEn 14.78
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_447.txt
/my_dir3/SetNewPatEn 14.784
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_448.txt
/my_dir3/SetNewPatEn 14.788
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_449.txt
/my_dir3/SetNewPatEn 14.792
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_450.txt
/my_dir3/SetNewPatEn 14.796
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_451.txt
/my_dir3/SetNewPatEn 14.8
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_452.txt
/my_dir3/SetNewPatEn 14.804
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_453.txt
/my_dir3/SetNewPatEn 14.808
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_454.txt
/my_dir3/SetNewPatEn 14.812
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_455.txt
/my_dir3/SetNewPatEn 14.816
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_456.txt
/my_dir3/SetNewPatEn 14.82
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_457.txt
/my_dir3/SetNewPatEn 14.824
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_458.txt
/my_dir3/SetNewPatEn 14.828
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_459.txt
/my_dir3/SetNewPatEn 14.832
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_460.txt
/my_dir3/SetNewPatEn 14.836
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_461.txt
/my_dir3/SetNewPatEn 14.84
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_462.txt
/my_dir3/SetNewPatEn 14.844
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_463.txt
/my_dir3/SetNewPatEn 14.848
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_464.txt
/my_dir3/SetNewPatEn 14.852
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_465.txt
/my_dir3/SetNewPatEn 14.856
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_466.txt
/my_dir3/SetNewPatEn 14.86
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_467.txt
/my_dir3/SetNewPatEn 14.864
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_468.txt
/my_dir3/SetNewPatEn 14.868
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_469.txt
/my_dir3/SetNewPatEn 14.872
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_470.txt
/my_dir3/SetNewPatEn 14.876
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_471.txt
/my_dir3/SetNewPatEn 14.88
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_472.txt
/my_dir3/SetNewPatEn 14.884
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_473.txt
/my_dir3/SetNewPatEn 14.888
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_474.txt
/my_dir3/SetNewPatEn 14.892
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_475.txt
/my_dir3/SetNewPatEn 14.896
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_476.txt
/my_dir3/SetNewPatEn 14.9
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_477.txt
/my_dir3/SetNewPatEn 14.904
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_478.txt
/my_dir3/SetNewPatEn 14.908
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_479.txt
/my_dir3/SetNewPatEn 14.912
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_480.txt
/my_dir3/SetNewPatEn 14.916
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_481.txt
/my_dir3/SetNewPatEn 14.92
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_482.txt
/my_dir3/SetNewPatEn 14.924
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_483.txt
/my_dir3/SetNewPatEn 14.928
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_484.txt
/my_dir3/SetNewPatEn 14.932
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_485.txt
/my_dir3/SetNewPatEn 14.936
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_486.txt
/my_dir3/SetNewPatEn 14.94
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_487.txt
/my_dir3/SetNewPatEn 14.944
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_488.txt
/my_dir3/SetNewPatEn 14.948
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_489.txt
/my_dir3/SetNewPatEn 14.952
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_490.txt
/my_dir3/SetNewPatEn 14.956
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_491.txt
/my_dir3/SetNewPatEn 14.96
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_492.txt
/my_dir3/SetNewPatEn 14.964
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_493.txt
/my_dir3/SetNewPatEn 14.968
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_494.txt
/my_dir3/SetNewPatEn 14.972
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_495.txt
/my_dir3/SetNewPatEn 14.976
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_496.txt
/my_dir3/SetNewPatEn 14.98
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_497.txt
/my_dir3/SetNewPatEn 14.984
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_498.txt
/my_dir3/SetNewPatEn 14.988
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_499.txt
/my_dir3/SetNewPatEn 14.992
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_500.txt
/my_dir3/SetNewPatEn 14.996
/run/beamOn 5000000

/my_dir1/SetNewResPath /mnt/hgfs/VMplayer/UMG3.3/Res_501.txt
/my_dir3/SetNewPatEn 15
/run/beamOn 5000000

